spring.application.name=sistema-ventas

# CONFIGURACIÓN DEL SERVIDOR
server.port=8081

# CONFIGURACIÓN DE BASE DE DATOS - PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/sistema_ventas_db
spring.datasource.username=postgres
#Cambiar por su contraseña
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver


# CONFIGURACIÓN JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true


# CONFIGURACIÓN THYMELEAF
spring.thymeleaf.cache=false
spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML5
spring.thymeleaf.encoding=UTF-8


# CONFIGURACIÓN SPRING SECURITY
spring.security.user.name=admin
spring.security.user.password=admin123


# LOGGING
logging.level.com.empresa.sistema_ventas=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE


# DEVTOOLS
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true


# MENSAJES DE ERROR
server.error.include-message=always
server.error.include-binding-errors=always